### ISSUE TITLE
switch from cjs to esm?

### ISSUE THREAD

**Issue by jimmywarting** [test-runner-js/oneline-view#1]
sindresorhus is converting all his 1k modules to ESM only... https://github.com/sindresorhus/meta/discussions/15
To update string-length and keep using it you would have to switch to ESM only as well...

**Comment by 75lb** [comment]
Hi, yes i have been moving the codebase to ESM for a year or two already.. although I still support CommonJS where possible (which, so far, has been in all projects except those supporting dynamic plug-in loads like renamer and local-web-server).. 

To support CommonJS, I use conditional exports (see node docs) alongside the native ESM code and a rollup build for the CJS..

I will update my Contributing guide with all this info, today hopefully..

**Comment by jimmywarting** [comment]
Do you want me to make a PR that switches this to ESM, and updates the dependency?
if so then i will add a `"type": "module"` in package.json too

**Comment by 75lb** [comment]
If you are submitting a fix or new feature, yes please change it to ESM too otherwise it is fine as it is, thanks.. this test-runner project is not quite ready - not quite v1.0 yet.. it is fully functional but i have a few things left to add before I invite participation..

**Comment by jimmywarting** [comment]
the notable change i found was that the next major ESM version of string length was an updated [char-regex](https://github.com/sindresorhus/string-length/commit/e681f7d46d02de037b13835782b7606ff8b1d589#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R39), which in turn changed how it calculates some string length: like this: https://github.com/sindresorhus/string-length/commit/e681f7d46d02de037b13835782b7606ff8b1d589#diff-13876b4beb64b9f156474dc78f9c923952a7ca210d4507b6b3135bbe244f8a60R7

**Comment by jimmywarting** [comment]
otherwise not so much new features...

**Comment by 75lb** [comment]
ok, thanks for the char-regex warning 👍

**Comment by jimmywarting** [comment]
This was just mostly assumptions, didn't go so much into dept if i'm correct or not
